enable_language(C)
memtable_fetch(wormhole https://github.com/wuxb45/wormhole.git
  31dfd2b1e67e5f709c78b018cf4abaecadad8b72)
memtable_patch(${wormhole_SOURCE_DIR} ${PROJECT_SOURCE_DIR}/cmake/patches/wormhole-asm.patch)
memtable_patch(${wormhole_SOURCE_DIR} ${PROJECT_SOURCE_DIR}/cmake/patches/wormhole-unaligned.patch)
add_library(memtable_wormhole STATIC
  ${wormhole_SOURCE_DIR}/lib.c ${wormhole_SOURCE_DIR}/kv.c ${wormhole_SOURCE_DIR}/wh.c)
set_target_properties(memtable_wormhole PROPERTIES C_STANDARD 17 C_EXTENSIONS ON)
target_include_directories(memtable_wormhole SYSTEM PUBLIC ${wormhole_SOURCE_DIR})
target_link_libraries(memtable_wormhole PUBLIC Threads::Threads m)
target_compile_definitions(memtable_wormhole PRIVATE NOSIGNAL=1)
target_compile_options(memtable_wormhole PRIVATE -msse4.2)
target_sources(memtable_bench_index PRIVATE src/wormhole_index.cc)
target_compile_definitions(memtable_bench_index PRIVATE MEMTABLE_BENCH_HAVE_WORMHOLE=1)
target_link_libraries(memtable_bench_index PRIVATE memtable_wormhole)
