enable_language(C)
memtable_fetch(wormhole https://github.com/wuxb45/wormhole.git
  31dfd2b1e67e5f709c78b018cf4abaecadad8b72)
memtable_patch(${wormhole_SOURCE_DIR} ${PROJECT_SOURCE_DIR}/cmake/patches/wormhole-asm.patch)
memtable_patch(${wormhole_SOURCE_DIR} ${PROJECT_SOURCE_DIR}/cmake/patches/wormhole-unaligned.patch)
add_library(memtable_wormhole STATIC
  ${wormhole_SOURCE_DIR}/lib.c ${wormhole_SOURCE_DIR}/kv.c ${wormhole_SOURCE_DIR}/wh.c)
set_target_properties(memtable_wormhole PROPERTIES C_STANDARD 17 C_EXTENSIONS ON)
target_include_directories(memtable_wormhole SYSTEM PUBLIC ${wormhole_SOURCE_DIR})
target_link_libraries(memtable_wormhole PUBLIC Threads::Threads m)
target_compile_definitions(memtable_wormhole PRIVATE NOSIGNAL=1)
set(wormhole_arch "${CMAKE_SYSTEM_PROCESSOR}")
if(APPLE AND CMAKE_OSX_ARCHITECTURES)
  set(wormhole_arch "${CMAKE_OSX_ARCHITECTURES}")
endif()
if(wormhole_arch MATCHES "^(arm64|aarch64)$")
  target_compile_options(memtable_wormhole PRIVATE -march=armv8-a+crc)
elseif(wormhole_arch MATCHES "^(x86_64|AMD64)$")
  target_compile_options(memtable_wormhole PRIVATE -msse4.2)
else()
  message(FATAL_ERROR "Wormhole requires x86_64 with SSE4.2 or ARM64 with CRC")
endif()
target_sources(memtable_bench_index PRIVATE src/wormhole_index.cc)
target_compile_definitions(memtable_bench_index PRIVATE MEMTABLE_BENCH_HAVE_WORMHOLE=1)
target_link_libraries(memtable_bench_index PRIVATE memtable_wormhole)
